logIOT/urls.py
from django.conf.urls import include, url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'logIOT'

urlpatterns = [
    url(r'^$', views.DevicesView.as_view(), name='devices'),
    url(r'device/(?P<pk>[0-9]+)/$', views.DeviceDetailView.as_view(), name='device-detail'),
    url(r'device/add/$', views.DeviceFormView.as_view(), name='device-add'),
    url(r'device/(?P<pk>[0-9]+)/update/$', views.DeviceUpdateView.as_view(), name='device-update'),
    url(r'device/(?P<pk>[0-9]+)/delete/$', views.DeviceDeleteView.as_view(), name='device-delete'),
    url(r'api/devices/', views.ApiDeviceList.as_view(), name='api-devicelist'),
    url(r'channel/(?P<pk>[0-9]+)/$', views.ChannelDetailView.as_view(), name='channel-detail'),
    #url(r'channel/(?P<pk>[0-9]+)/data.plot$', plots.plotChannelData, name='channel-plot'),
    url(r'channel/add/$', views.ChannelFormView.as_view(), name='channel-add'),
    url(r'channel/(?P<pk>[0-9]+)/update/$', views.ChannelUpdateView.as_view(), name='channel-update'),
    url(r'channel/(?P<pk>[0-9]+)/delete/$', views.ChannelDeleteView.as_view(), name='channel-delete'),
    url(r'api/data/', views.ApiDataLogging.as_view(), name='api-datalogging'),
    url(r'dashboard/$', views.DashboardView.as_view(), name='dashboard'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^about/$', views.about, name='about'),
]

mothership/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^main/', include('main.urls')),
    url(r'^logIOT/', include('logIOT.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('userControl.urls')),
]

# If in development mode...
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

userControl/urls.py
from django.conf.urls import url
from . import views

app_name = 'userControl'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'modify/(?P<pk>[0-9]+)/$', views.UserUpdateView.as_view(), name='user-update'),
    url(r'modify/(?P<pk>[0-9]+)/delete/$', views.UserDeleteView.as_view(), name='user-delete'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^(?P<username>\w+)/$', views.UserDetailView.as_view(), name='user-detail'),
    url(r'^obtain-api-token/$', views.CreateApiTokenView.as_view(), name='apitoken-create'),
]

main/models.py
from django.db import models

main/views.py
from django.shortcuts import render
from logIOT.models import Device
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'logIOT/index.html'

    def get_queryset(self):
        public_devices = Device.objects.filter(public=True)
        return  public_devices


def about(request):
    template_name = 'main/about.html'
    return render(request, template_name)

main/templates/main/about.html
{% extends 'main/base_MDL.html' %}

{% block body %}
    <h1>About</h1>
    <p>This page is a work in progress</p>
    <br>
    <p>Created by Will Hunt - 2016</p>
    <p>Django on Pythonanywhere</p>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mothership{% endblock %}</title>

    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
    <link rel="icon" href="{% static 'main/images/M_icon.png' %}" />
    {% block static %}{% endblock %}
</head>

<body>
    <!-- Header Nav Bar -->
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="glyphicon glyphicon-menu-hamburger"></span>
                </button>
                <!-- Brand -->
                <a class="navbar-brand" href="{% url 'main:index' %}">Mothership</a>
            </div>

            <!-- Items -->
            <div class ="collapse navbar-collapse" id="topNavBar">

                <!-- Buttons left -->
                <ul class="nav navbar-nav navbar-left">
                    <li class="active"><a href="#">Dashboard</a></li>
                    <li class=""><a href="{% url 'logIOT:devices' %}">Devices</a></li>
                </ul>

                <!-- Buttons right -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Differnt options depending on login status -->
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'userControl:user-detail' user.username %}">
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Account
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'logIOT:device-add' %}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Device
                                </a>
                            </li>
                            <!-- Extra for staff -->
                            {% if user.is_staff %}
                            <li>
                                <a href="{% url 'admin:index' %}">
                                    <span class="glyphicon glyphicon-tower" aria-hidden="true"></span>&nbsp; Admin Panel
                                </a>
                            </li>
                            {% endif %}
                            <li>
                                <a href="{% url 'userControl:logout' %}">
                                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            User<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'userControl:register' %}">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp; Register
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'userControl:login' %}">
                                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                                </a>
                            </li>
                        </ul>
                    </li>

                    {% endif %}
                </ul>

                <!-- Search box -->
                <form class="navbar-form navbar-right nav_search" role="search" method="get" action="#">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="Search" value="">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">Go</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </nav>

    <div class="content">
        <!-- Insert body from other templates -->
        {% block body %}
        {% endblock %}
    </div>


    <!-- Footer -->
    <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="container-fluid">
            <div class="nav navbar-left">
                <p class="navbar-text">Mothership | Hosted on <a href="https://www.pythonanywhere.com">Pythonanywhere</a></p>
            </div>
            <div class="nav navbar-right">
                <a class="navbar-text" href="{% url 'main:about' %}">About</a>
            </div>
        </div>
    </nav>


</body>

</html>

main/templates/main/base_MDL.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Mothership{% endblock %}</title>

    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"></link>
    <!-- <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey-deep_orange.min.css"></link> -->
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue_grey-red.min.css"></link>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css"></link>
    <link rel="stylesheet" href="{% static 'main/style_MDL.css' %}" type="text/css"></link>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Baloo+Chettan" type='text/css'></link>
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link rel="icon" href="{% static 'main/images/M_icon.png' %}"></link>
    {% block static %}{% endblock %}

    <!-- Includes for django-material --><!--
    {% include 'material/includes/material_css.html' %}
    {% include 'material/includes/material_js.html' %}
    <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>-->

</head>

<body>
    <!-- MDL scrolling header -->
    <div class="dash-bill mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <!-- Header -->
        <header class="mdl-layout__header mdl-layout__header--scroll">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <a href={% url 'main:index' %}>
                    <span class="mdl-layout-title" id="header-title">Mothership</a>
                </span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>

                <!-- Search box (collapsable) -->
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
                    <label class="mdl-button mdl-js-button mdl-button--icon" for="search-field">
                        <i class="material-icons">search</i>
                    </label>
                    <div class="mdl-textfield__expandable-holder">
                      <input class="mdl-textfield__input" type="text" id="search-field">
                    </div>
                </div>

                <!-- Navigation -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    {% if user.is_authenticated %}
                        <a class="mdl-navigation__link mdl-typography--text-uppercase" href="">Dashboard</a>
                    {% endif %}
                    <a class="mdl-navigation__link mdl-typography--text-uppercase" href={% url 'logIOT:devices' %}>Devices</a>
                </nav>

                <!-- Account Button -->
                <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-layout--large-screen-only" id="accountbtn">
                    <i class="material-icons">account_circle</i>
                </button>
                <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="accountbtn">
                    {% if user.is_authenticated %}
                        <li class="mdl-menu__item">
                            <a href="{% url 'userControl:user-detail' user.username %}">Account</a>
                        </li>
                        {% if user.is_staff %}
                            <li class="mdl-menu__item">
                                <a href="{% url 'admin:index' %}">Admin Panel</a>
                            </li>
                        {% endif %}
                        <li class="mdl-menu__item">
                            <a href="{% url 'userControl:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="mdl-menu__item">
                            <a href="{% url 'userControl:login' %}">Login</a>
                        </li>
                        <li class="mdl-menu__item">
                            <a href="{% url 'userControl:register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Mothership</span>
                <nav class="mdl-navigation">
                    {% if user.is_authenticated %}
                        <a class="mdl-navigation__link" href="">Dashboard</a>
                    {% endif %}
                    <a class="mdl-navigation__link" href="{% url 'logIOT:devices' %}">Devices</a>
                    {% if user.is_authenticated %}
                        <a class="mdl-navigation__link" href="{% url 'logIOT:device-add' %}">Add Device</a>
                        <div class="drawer-separator"></div>
                        <a class="mdl-navigation__link" href="{% url 'userControl:user-detail' user.username %}">Account</a>
                        {% if user.is_staff %}
                            <a class="mdl-navigation__link" href="{% url 'admin:index' %}">Admin Panel</a>
                        {% endif %}
                        <a class="mdl-navigation__link" href="{% url 'userControl:logout' %}">Logout</a>
                    {% else %}
                        <div class="drawer-separator"></div>
                        <a class="mdl-navigation__link" href="{% url 'userControl:login' %}">Login</a>
                        <a class="mdl-navigation__link" href="{% url 'userControl:register' %}">Register</a>
                    {% endif %}
                </nav>
        </div>

        <main class="mdl-layout__content">
            <!-- Page content -->
            <div class="page-content">
                {% block body %}
                {% endblock %}
            </div>

            <!-- Footer -->
            <footer class="mdl-mini-footer">
                <div class="mdl-mini-footer__left-section">
                    <div class="mdl-logo">Mothership</div>
                    <ul class="mdl-mini-footer__link-list">
                        <li><a href="{% url 'main:about' %}">About</a></li>
                    </ul>
                </div>
                <div class="mdl-mini-footer__right-section">
                    <ul class="mdl-mini-footer__link-list">
                        <li><a href="https://www.pythonanywhere.com">Hosted of Pythonanywhere</a></li>
                    </ul>
                </div>
            </footer>
        </main>
    </div>

</body>
</html>

main/templates/main/index.html
{% extends 'main/base_MDL.html' %}

{% block body %}
    <h1>Homepage</h1>
    <br>
    <h2>Public Devices</h2>
    {% if object_list %}
        <ul>
            {% for device in object_list %}
            <li><a href="{% url 'logIOT:device-detail' device.id %}">{{ device.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>No public channels</h3>
    {% endif %}
{% endblock %}