logIOT/urls.py
from django.conf.urls import include, url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'logIOT'

urlpatterns = [
    url(r'^$', views.DevicesView.as_view(), name='devices'),
    url(r'device/(?P<pk>[0-9]+)/$', views.DeviceDetailView.as_view(), name='device-detail'),
    url(r'device/add/$', views.DeviceFormView.as_view(), name='device-add'),
    url(r'device/(?P<pk>[0-9]+)/update/$', views.DeviceUpdateView.as_view(), name='device-update'),
    url(r'device/(?P<pk>[0-9]+)/delete/$', views.DeviceDeleteView.as_view(), name='device-delete'),
    url(r'api/devices/', views.ApiDeviceList.as_view(), name='api-devicelist'),
    url(r'channel/(?P<pk>[0-9]+)/$', views.ChannelDetailView.as_view(), name='channel-detail'),
    #url(r'channel/(?P<pk>[0-9]+)/data.plot$', plots.plotChannelData, name='channel-plot'),
    url(r'channel/add/$', views.ChannelFormView.as_view(), name='channel-add'),
    url(r'channel/(?P<pk>[0-9]+)/update/$', views.ChannelUpdateView.as_view(), name='channel-update'),
    url(r'channel/(?P<pk>[0-9]+)/delete/$', views.ChannelDeleteView.as_view(), name='channel-delete'),
    url(r'api/data/', views.ApiDataLogging.as_view(), name='api-datalogging'),
    url(r'dashboard/$', views.DashboardView.as_view(), name='dashboard'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^about/$', views.about, name='about'),
]

mothership/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^main/', include('main.urls')),
    url(r'^logIOT/', include('logIOT.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('userControl.urls')),
]

# If in development mode...
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

logIOT/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse


class SensorType(models.Model):
    ''' Sensor types and unit information allowing conversion '''
    sensor_type = models.CharField(max_length=50)

    def __str__(self):
        return self.sensor_type


class SensorOption(models.Model):
    ''' Sensor types and unit information allowing conversion '''
    sensor_type = models.ForeignKey(SensorType, on_delete=models.CASCADE)
    units = models.CharField(max_length=15)
    base_unit = models.BooleanField(default=False) # Indicate if base unit
    base_multiplier = models.FloatField(default=0) # Converison multiplier to base unit
    base_offset = models.FloatField(default=0) # Converison offset to base unit

    def __str__(self):
        return self.units


class Device(models.Model):
    ''' Device that can have multiple sensors '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.CharField(max_length=100, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    public = models.BooleanField(default=False)
    date_created = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        ''' Returns absolute url using primary key keyword argument '''
        return reverse('logIOT:device-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Channel(models.Model):
    ''' Device channel '''
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    sensor_type = models.ForeignKey(SensorType, on_delete=models.CASCADE)
    units = models.ForeignKey(SensorOption, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        ''' Returns absolute url using primary key keyword argument '''
        return reverse('logIOT:channel-detail', kwargs={'pk': self.pk})


class Data(models.Model):
    ''' Channel Data '''
    # Get channel
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    time = models.DateTimeField(default=timezone.now)
    value = models.FloatField()

    def __str__(self):
        return self.channel.name + ': Data'

logIOT/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Div, ButtonHolder
from crispy_forms.bootstrap import Accordion, AccordionGroup, Tab
from .models import Device, Channel

# New device form class based upon Django model form
class DeviceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        # Call base calss constructor
        super(DeviceForm, self).__init__(*args, **kwargs)
        # If you pass FormHelper constructor a form instance,
        # it builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'registrationForm'
        self.helper.form_class = 'site_form form-horizontal'
        self.helper.label_class = 'col-xs-2 col-md-2'
        self.helper.field_class = 'col-xs-10 col-md-10'
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Fieldset('Device Details',
                'name',
                'description',
                'image'),
            Fieldset('Device Location',
                'latitude',
                'longitude'),
            Fieldset(' ',
                'public'),
            Div(
                Submit('submit', 'Save Device', css_class='btn btn-default'),
                css_class='col-xs-offset-2 col-md-offset-2')
        )

        #self.helper.layout.append(Submit('save', 'save'))

    class Meta:
        # Database model type (we are adding a Device)
        model = Device
        # Fields for model (same as in user models file)
        fields = ['name', 'description', 'image', 'latitude', 'longitude', 'public']
        # Add/override data for models fields
        labels = {
            'image': _('Image URL'),
            'public': _('Make public?'),
        }


class ChannelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        # Call base calss constructor
        super(ChannelForm, self).__init__(*args, **kwargs)
        # If you pass FormHelper constructor a form instance,
        # it builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'channelForm'
        self.helper.form_class = 'site_form form-horizontal'
        self.helper.label_class = 'col-xs-2 col-md-2'
        self.helper.field_class = 'col-xs-10 col-md-10'
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Fieldset('Channel Details',
                'name'),
            Fieldset('Sensor Details',
                'sensor_type',
                'units'),
            Div(
                Submit('submit', 'Save Channel', css_class='btn btn-default'),
                css_class='col-xs-offset-2 col-md-offset-2')
        )

        #self.helper.layout.append(Submit('save', 'save'))

    class Meta:
        # Database model type (we are adding a Device)
        model = Channel
        # Fields for model (same as in user models file)
        fields = ['name', 'sensor_type', 'units']
        # Add/override data for models fields
        labels = {
            'sensor_type': _('sensor type'),
        }

logIOT/views.py
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import Http404
from rest_framework import status, permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.generics import ListCreateAPIView
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from .models import Device, Channel
from .serializers import DeviceSerializer, DataSerializer
from .forms import DeviceForm, ChannelForm
from .permissions import IsOwnerOrReadOnly


class DevicesView(generic.ListView):
    template_name = 'logIOT/devices.html'

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            return Device.objects.filter(user=user)
        else:
            return Device.objects.filter(public=True)


class DeviceDetailView(generic.DetailView):
    model = Device
    template_name = 'logIOT/device_detail_MDL.html'


class DeviceFormView(View):
    # Choose form blueprint
    form_class = DeviceForm # Use form created in forms.py
    template_name = 'logIOT/device_form.html'

    # Display blank form for new user
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # Process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # Create user object from form but not saved to database
            new_device = form.save(commit=False)
            # Clean and normalise data
            new_device.name = form.cleaned_data['name']
            new_device.description = form.cleaned_data['description']
            new_device.latitude = form.cleaned_data['latitude']
            new_device.longitude = form.cleaned_data['longitude']
            new_device.image = form.cleaned_data['image']
            new_device.user = request.user
            new_device.save()
            return redirect(new_device)

        return render(request, self.template_name, {'form': form})


class DeviceUpdateView(UpdateView):
    # Automatically will render <modelname>_form.html
    model = Device
    form_class = DeviceForm

    def get_object(self, queryset=None):
        # Hook to ensure object is owned by request.user
        object = super(DeviceUpdateView, self).get_object()
        if not object.user == self.request.user:
            raise Http404
        return object


class DeviceDeleteView(DeleteView):
    model= Device
    success_url = reverse_lazy('main:index')

    def get_object(self, queryset=None):
        # Hook to ensure object is owned by request.user
        object = super(DeviceDeleteView, self).get_object()
        if not object.user == self.request.user:
            raise Http404
        return object


class ChannelDetailView(generic.DetailView):
    model = Channel
    template_name = 'logIOT/channel_detail_MDL.html'


class ChannelFormView(View):
    # Choose form blueprint
    form_class = ChannelForm # Use form created in forms.py
    template_name = 'logIOT/channel_form.html'

    # Display blank form for new user
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # Process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # Create user object from form but not saved to database
            new_channel = form.save(commit=False)
            # Clean and normalise data
            new_channel.name = form.cleaned_data['name']
            new_channel.sensor_type = form.cleaned_data['sensor_type']
            new_channel.units = form.cleaned_data['units']
            # Get device id, if none choose ''
            new_channel.device = Device.objects.get(pk=request.GET.get('device_id', ''))
            new_channel.save()
            return redirect(new_channel)

        return render(request, self.template_name, {'form': form})


class ChannelUpdateView(UpdateView):
    # Automatically will render <modelname>_form.html
    model = Channel
    form_class = ChannelForm

    def get_object(self, queryset=None):
        # Hook to ensure channel's device is owned by request.user
        object = super(ChannelUpdateView, self).get_object()
        if not object.device.user == self.request.user:
            raise Http404
        return object


class ChannelDeleteView(DeleteView):
    model= Channel
    success_url = reverse_lazy('main:index')

    def get_object(self, queryset=None):
        # Hook to ensure channel's device is owned by request.user
        object = super(ChannelDeleteView, self).get_object()
        if not object.device.user == self.request.user:
            raise Http404
        return object


class ApiDeviceList(ListCreateAPIView):
    queryset = Device.objects.all()
    serializer_class = DeviceSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class ApiDataLogging(APIView):
    ''' Adds data for device channel via API '''
    # For api data loggong use api token to authenticate
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        pass

    def post(self, request):
        serializer = DataSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class IndexView(View):
    template_name = 'logIOT/index.html'

    def get_queryset(self):
        public_devices = Device.objects.filter(public=True)
        return  public_devices


class DashboardView(View):
    template_name = 'logIOT/dashboard.html'

logIOT/templates/logIOT/channel_detail.html
{% extends 'main/base_MDL.html' %}

{% block title %}Channel Details{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.js"></script>
{% endblock %}

{% block body %}
    <!-- Channel details -->
    <h1>{{ channel.name }}</h1>
    <br>
    <table id="tableDetails">
        <tr>
            <th>Device</td>
            <td><a href="{% url 'logIOT:device-detail' channel.device.id %}">{{ channel.device }}</a></td>
        </tr>
        <tr>
            <th>Type</td>
            <td>{{ channel.sensor_type }}</td>
        </tr>
        <tr>
            <th>Units</td>
            <td>{{ channel.units }}</td>
        </tr>
    </table>
    <br>
    <!-- ChartJS graph -->
    <div class="smallChart" style="width:400px">
        <canvas id="channelChart" width="400" height="300"></canvas>
        <script src="{% static 'logIOT/chart.js' %}"></script>
    </div>

    <br>
    <p>Created: {{ channel.date_created }}</p>

    <!-- Buttons (only for logged in users) -->
    {% if user == channel.device.user %}
    <br>
    <form action="{% url 'logIOT:channel-update' channel.id %}" method="get" style="display: inline;">
        {% csrf_token %}
        <input type="hidden" name="channel_id" value="{{ channel.id }}"/>
        <button type="submit" class="btn btn-default btn-sm">Edit</button>
    </form>
    <form action="{% url 'logIOT:channel-delete' channel.id %}" method="get" style="display: inline;">
        {% csrf_token %}
        <input type="hidden" name="channel_id" value="{{ channel.id }}"/>
        <button type="submit" class="btn btn-default btn-sm">Delete</button>
    </form>
    {% endif %}

{% endblock %}

logIOT/templates/logIOT/channel_detail_MDL.html
{% extends 'main/base_MDL.html' %}

{% block title %}Channel Details{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style_MDL.css' %}"></link>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.js"></script>
{% endblock %}

{% block body %}
    <div class="logIOT-layout logIOT-channel-detail content-grid mdl-grid" id="channel-content">
        <div class="mdl-card logIOT-detail-pane mdl-cell mdl-cell--6-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
            <div class="mdl-card__title">
                <h3 class="mdl-card__title-text">{{ channel.name }}</h3>
            </div>
            <div class="mdl-card__supporting-text mdl-card--expand">
                <table id="tableDetails">
                    <tr>
                        <th>Device</th>
                        <td><a href="{% url 'logIOT:device-detail' channel.device.id %}">{{ channel.device }}</a></td>
                    </tr>
                    <tr>
                        <th>Type</th>
                        <td>{{ channel.sensor_type }}</td>
                    </tr>
                    <tr>
                        <th>Units</th>
                        <td>{{ channel.units }}</td>
                    </tr>
                </table>
                <br>
                <p>Created: {{ channel.date_created }}</p>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                {% if channel.device.public %}
                    <div class="mdl-card__supporting-text">PUBLIC DEVICE</div>
                {% endif %}
                <!-- Buttons (only for logged in users) -->
                {% if user == channel.device.user %}
                    <div class="mdl-layout-spacer"></div>
                	<!-- Add device button -->
        			<button class="mdl-button mdl-js-button mdl-button--icon" id="edit-device-menu" ><i class="material-icons">settings</i></button>
                    <ul class="mdl-menu mdl-menu--top-right mdl-js-menu" for="edit-device-menu">
                        <li class="mdl-menu__item">
                            <form action="{% url 'logIOT:channel-update' channel.id %}" method="get" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="channel_id" value="{{ channel.id }}"/>
                                <button class="mdl-button mdl-js-button mdl-js-ripple-effect" type="submit">Edit Channel</button>
                            </form>
                        </li>
                        <li class="mdl-menu__item">
                            <form action="{% url 'logIOT:channel-delete' channel.id %}" method="get" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="channel_id" value="{{ channel.id }}"/>
                                <button class="mdl-button mdl-js-button mdl-js-ripple-effect" type="submit">Delete Channel</button>
                            </form>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
        <div class="mdl-card mdl-cell mdl-cell--6-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
            <!-- Channel data plot -->
            <div class="logIOT-card-chart" style="width:400px" id="channel-chart">
                <script>
                    var channel_name = '{{ channel.name }}';
                    var y_label = '{{ channel.sensor_type }} ({{ channel.units }})';
                    var x_data = [];
                    var y_data = [];
                    {% for data in channel.data_set.all %}
                        x_data.push(new Date({{ data.time|date:"U" }} * 1000));
                        y_data.push({{ data.value }});
                    {% endfor %}
                </script>
                <canvas id="channelChart" width="400" height="300"></canvas>
                <script src="{% static 'logIOT/chart_channels.js' %}"></script>
            </div>
        </div>

    </div>

{% endblock %}

logIOT/templates/logIOT/channel_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block title %}New Channel{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style.css' %}" />
{% endblock %}

{% block body %}
    <div class="container">
        <div class="text-logo">Mothership Channel</div>

            {% crispy form %}

        </div>
    </div>
{% endblock %}

logIOT/templates/logIOT/dashboard.html
{% extends 'main/base_MDL.html' %}

{% block title %}Dashboard{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style.css' %}" />
{% endblock %}

{% block body %}


{% endblock %}

logIOT/templates/logIOT/device_confirm_delete.html
{% extends 'main/base_MDL.html' %}

{% block title %}Device Details{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style.css' %}" />
{% endblock %}

{% block body %}

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>

{% endblock %}

logIOT/templates/logIOT/device_detail.html
{% extends 'main/base.html' %}

{% block title %}Device Details{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style.css' %}" />
{% endblock %}

{% block body %}
    <h1>{{ device.name }}</h1>
    {{ device.description }}
    <br>
    {% if device.image %}
        <img src="{{ device.image }}" class="img-device" />
    {% else %}
        <h3>No image</h3>
    {% endif %}


    <ul>
        {% for channel in device.channel_set.all %}
        <li><a href="{% url 'logIOT:channel-detail' channel.id %}">{{ channel.name }}: {{ channel.sensor_type }}</a></li>
        {% endfor %}
    </ul>

    <!-- Channel data plot -->
    <img src="data.plot">

    <!-- Buttons (only for logged in users) -->
    {% if user == device.user %}
    <form action="{% url 'logIOT:channel-add' %}" method="get">
        {% csrf_token %}
        <input type="hidden" name="device_id" value="{{ device.id }}"/>
        <button type="submit" class="btn btn-link"><span class="glyphicon glyphicon-plus"></span> Add Channel</button>
    </form>
    <br>
    <form action="{% url 'logIOT:device-update' device.id %}" method="get" style="display: inline;">
        {% csrf_token %}
        <input type="hidden" name="device_id" value="{{ device.id }}"/>
        <button type="submit" class="btn btn-default btn-sm">Edit</button>
    </form>
    <form action="{% url 'logIOT:device-delete' device.id %}" method="get" style="display: inline;">
        {% csrf_token %}
        <input type="hidden" name="device_id" value="{{ device.id }}"/>
        <button type="submit" class="btn btn-default btn-sm">Delete</button>
    </form>
    {% endif %}

{% endblock %}

logIOT/templates/logIOT/device_detail_MDL.html
{% extends 'main/base_MDL.html' %}

{% block title %}Device Details{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style_MDL.css' %}"></link>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.js"></script>
    <script src="{% static 'logIOT/map.js' %}"></script>
{% endblock %}

{% block body %}
<!-- Creat grid for cards -->
    <div class="logIOT-layout logIOT-device-detail content-grid mdl-grid" id="device-content">
        <!-- Card for device details -->
        <div class="mdl-card logIOT-detail-pane mdl-cell mdl-cell--8-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
            <!-- Create grid for laying out items (nested) on info card -->
            <div class="mdl-grid mdl-grid--no-spacing">
                <!-- Container for image -->
                <div class="device-image mdl-cell mdl-cell--5-col-desktop mdl-cell--3-col-tablet mdl-cell--4-col-phone">
                    <div class="mdl-card__media" style="background: url('{{ device.image }}') center / cover;">
                    </div>
                </div>
                <!-- Container for info -->
                <div class="mdl-card mdl-cell mdl-cell--7-col-desktop mdl-cell--5-col-tablet mdl-cell--4-col-phone">
                    <div class="mdl-card__title">
                        <h3 class="mdl-card__title-text">{{ device.name }}</h3>
                    </div>
                    <div class="mdl-card__supporting-text mdl-card--expand">
                        <p>{{ device.description }}</p>
                        <ul>
                            {% for channel in device.channel_set.all %}
                            <li><a href="{% url 'logIOT:channel-detail' channel.id %}">{{ channel.name }}: {{ channel.sensor_type }}</a></li>
                            {% endfor %}
                        </ul>
                        <br>
                        <p>Created: {{ device.date_created }}</p>
                    </div>

                    <!-- Container for card actions -->
                    <div class="mdl-card__actions mdl-card--border">
                        {% if device.public %}
                            <div class="mdl-card__supporting-text">PUBLIC DEVICE</div>
                        {% endif %}
                        <!-- Buttons (only for logged in users) -->
                        {% if user == device.user %}
                            <div class="mdl-layout-spacer"></div>
                        	<!-- Add device button -->
                            <form action="{% url 'logIOT:channel-add' %}" method="get">
                                {% csrf_token %}
                                <input type="hidden" name="device_id" value="{{ device.id }}"/>
                                <button type="submit" class="mdl-button mdl-js-button mdl-button--icon"><i class="material-icons">add</i></button>
                            </form>
                			<button class="mdl-button mdl-js-button mdl-button--icon" id="edit-device-menu" ><i class="material-icons">settings</i></button>
                            <ul class="mdl-menu mdl-menu--top-right mdl-js-menu" for="edit-device-menu">
                                <li class="mdl-menu__item">
                                    <form action="{% url 'logIOT:device-update' device.id %}" method="get" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="device_id" value="{{ device.id }}"/>
                                        <button class="mdl-button mdl-js-button mdl-js-ripple-effect" type="submit">Edit Device</button>
                                    </form>
                                </li>
                                <li class="mdl-menu__item">
                                    <form action="{% url 'logIOT:device-delete' device.id %}" method="get" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="device_id" value="{{ device.id }}"/>
                                        <button class="mdl-button mdl-js-button mdl-js-ripple-effect" type="submit">Delete Device</button>
                                    </form>
                                </li>
                            </ul>
                        {% endif %}
                    </div><!-- End of card actions -->
                </div><!-- End of info container -->
            </div><!-- End of detail view layout grid -->
        </div><!-- End of detail view card -->

        <!-- Map card -->
        <div class="mdl-card mdl-cell mdl-cell--4-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
            <div id="map-device">
                <!-- Pass in variables from Django to javascript -->
                <script>
                    var lat = {{ device.latitude }};
                    var lng = {{ device.longitude }};
                </script>
                <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAR8rxYroitjOPr_G-Adn6iFEHJNpOyIc8&callback=initDeviceMap">
                </script>
            </div>
        </div>
    </div><!-- Enf of content grid -->

{% endblock %}

logIOT/templates/logIOT/device_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block title %}New Device{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style.css' %}" />
{% endblock %}

{% block body %}
    <div class="container">
        <div class="text-logo">Mothership Device</div>

            {% crispy form %}

        </div>
    </div>
{% endblock %}

logIOT/templates/logIOT/device_form_MDL.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block title %}New Device{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'logIOT/style.css' %}" />
{% endblock %}

{% block body %}
    <div class="container">
        <div class="text-logo">Mothership Device</div>

            {% crispy form %}

        </div>
    </div>
{% endblock %}

logIOT/templates/logIOT/devices.html
{% extends 'main/base_MDL.html' %}

{% block title %}Devices{% endblock %}

{% block body %}
    <h1>All Devices</h1>
    <br>
    {% if object_list %}
        <ul>
            {% for device in object_list %}
            <li><a href="{% url 'logIOT:device-detail' device.id %}">{{ device.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>No devices</h3>
    {% endif %}
{% endblock %}

logIOT/templates/logIOT/rough.html
<!-- Buttons (only for logged in users) -->
            {% if user == device.user %}
                <!-- Add device button -->
                <form action="{% url 'logIOT:channel-add' %}" method="get">
                    {% csrf_token %}
                    <input type="hidden" name="device_id" value="{{ device.id }}"/>
                    <button type="submit" class="mdl-button mdl-js-button mdl-button--icon"><i class="material-icons">add</i></button>
                </form>
                <!-- Menu button -->
                <button class="mdl-button mdl-js-button mdl-button--icon" id="edit-device-menu" ><i class="material-icons">settings</i></button>
                <ul class="mdl-menu mdl-menu--top-right mdl-js-menu" for="edit-device-menu">
                    <li class="mdl-menu__item">
                        <form action="{% url 'logIOT:device-update' device.id %}" method="get" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="device_id" value="{{ device.id }}"/>
                            <button class="mdl-button mdl-js-button mdl-js-ripple-effect" type="submit">Edit Device</button>
                        </form>
                    </li>
                    <li class="mdl-menu__item">
                        <form action="{% url 'logIOT:device-delete' device.id %}" method="get" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="device_id" value="{{ device.id }}"/>
                            <button class="mdl-button mdl-js-button mdl-js-ripple-effect" type="submit">Delete Device</button>
                        </form>
                    </li>
                </ul>
            {% else %}
                <div class="mdl-card__supporting-text">PUBLIC DEVICE</div>
            {% endif %}