main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^about/$', views.about, name='about'),
]

mothership/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^main/', include('main.urls')),
    url(r'^logIOT/', include('logIOT.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('userControl.urls')),
]

# If in development mode...
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

userControl/urls.py
from django.conf.urls import url
from . import views

app_name = 'userControl'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'modify/(?P<pk>[0-9]+)/$', views.UserUpdateView.as_view(), name='user-update'),
    url(r'modify/(?P<pk>[0-9]+)/delete/$', views.UserDeleteView.as_view(), name='user-delete'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^(?P<username>\w+)/$', views.UserDetailView.as_view(), name='user-detail'),
    url(r'^obtain-api-token/$', views.CreateApiTokenView.as_view(), name='apitoken-create'),
]

userControl/models.py
from django.db import models
from rest_framework.authtoken.models import Token



def create_api_token(user):#
    ''' Create api token for given user '''
    token = Token.objects.create(user=user)
    return token

userControl/forms.py
# Get base user class
from django.contrib.auth.models import User
from django import forms

# New user form class based upon Django base user model form
class UserForm(forms.ModelForm):
    # Set password field type
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password', 'class': 'mdl-textfield__input'}))

    class Meta:
        # Database model type (we are adding a user)
        model = User
        # Fields for model (same as in user models file)
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        # Add/overide data for models fields
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'username', 'class': 'mdl-textfield__input'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'first name', 'class': 'mdl-textfield__input'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'last name', 'class': 'mdl-textfield__input'}),
            'email': forms.TextInput(attrs={'placeholder': 'email address', 'class': 'mdl-textfield__input'}),
        }

userControl/views.py
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.generic import View, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.http import HttpResponse, Http404, HttpResponseRedirect
from rest_framework.authtoken.models import Token
from .forms import UserForm


def index(request):
    return HttpResponse("<h1>How did you get here?</h1>")


class UserFormView(View):
    # Choose form blueprint
    form_class = UserForm # Use form created in forms.py
    template_name = 'userControl/registration_form_MDL.html'

    # Display blank form for new user
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # Process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # Create user object from form but not saved to database
            user = form.save(commit=False)
            # Clean and normalise data
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #Returns user object if credentials are correct
            user = authenticate(username=username, password=password)
            # Check if user is in database
            if user is not None:
                # Check user is not banned/disabled
                if user.is_active:
                    login(request,user)
                    # Redirect to homepage after succesful login
                    return redirect('main:index')

        return render(request, self.template_name, {'form': form})


class UserUpdateView(UpdateView):
    # Automatically will render <modelname>_form.html
    model = User
    form_class = UserForm
    template_name = 'userControl/registration_form.html'

    def get_object(self, queryset=None):
        # Hook to ensure object is owned by request.user
        object = super(UserUpdateView, self).get_object()
        if not object == self.request.user:
            raise Http404
        return object


class UserDeleteView(DeleteView):
    model= User
    success_url = reverse_lazy('main:index')

    def get_object(self, queryset=None):
        # Hook to ensure object is owned by request.user
        object = super(UserDeleteView, self).get_object()
        if not object == self.request.user:
            raise Http404
        return object


def user_login(request):
    template_name = 'userControl/login.html'

    # Display blank form for new user
    if request.method == 'GET':
        return render(request, template_name)

    # Process form data
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        # Check if user is in database
        if user is not None:
            # Check user is not banned/disabled
            if user.is_active:
                login(request,user)
                # Redirect to homepage after succesful login
                return redirect('main:index')
        else:
            error_message = 'Username or password not recognised'
            return render(request, template_name, {'error_message': error_message})



def user_logout(request):
    logout(request)
    return redirect('main:index')


class UserDetailView(DetailView):
    ''' View showing user accoutn information '''
    #model = User
    template_name = 'userControl/user_detail.html'
    # Override get method to allow username in url
    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get("username"))

    def get_context_data(self, **kwargs):
        # Call base implementation first tp get context
        context = super(UserDetailView, self).get_context_data(**kwargs)
        # Get current user
        user = User.objects.filter(username=self.kwargs.get("username"))
        # Add in a QuerySet of API tokens
        context['api_tokens'] = Token.objects.filter(user=user)
        return context


class CreateApiTokenView(View):

    def post(self, request, *args, **kwargs):
        # Check for existing user token and delete
        if Token.objects.filter(user=request.user):
            Token.objects.filter(user=request.user).delete()
        Token.objects.create(user=request.user)
        redirect_url = reverse('userControl:user-detail', kwargs={'username': request.user.username})
        return HttpResponseRedirect(redirect_url)

userControl/templates/userControl/login.html
{% extends 'main/base.html' %}

{% block title %}Login{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'userControl/style.css' %}" />
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="Absolute-Center is-Responsive">
                <div class="text-logo text-center">Mothership</div>
                <div class="col-sm-12 col-md-10 col-md-offset-1">

                    {% if error_message %}
                        <p class="text-danger text-center">{{ error_message }}</p>
                    {% endif %}

                    <form id="loginForm" class="site_form" action="" method="post">
                        {% csrf_token %}
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input class="form-control" type="text" name='username' placeholder="username"/>
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input class="form-control" type="password" name='password' placeholder="password"/>
                          </div>
                        <div class="form-group">
                            <button type="sumbit" class="btn btn-def btn-block">Login</button>
                        </div>
                        <div class="form-group text-center">
                            <a href="#">Forgot Password</a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
{% endblock %}

userControl/templates/userControl/registration_form.html
{% extends 'main/base.html' %}
{% block title %}Registration{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'userControl/style.css' %}" />
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="Absolute-Center is-Responsive">
                <div class="text-logo text-center">sign up to the</div>
                <div class="text-logo text-center">Mothership</div>
                <div class="col-sm-12 col-md-10 col-md-offset-1">

                    {% if error_message %}
                        <p class="text-danger text-center">{{ error_message }}</p>
                    {% endif %}

                    <form id="registrationForm" class="site_form" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <span class="text-danger small">{{ field.errors }}</span>
                                {{ field }}
                            </div>
                        {% endfor %}

                        <div class="form-group">
                            <button type="sumbit" class="btn btn-def btn-block">Register</button>
                        </div>

                        <div class="form-group text-center">
                            <br>
                            <a href="{% url 'userControl:login' %}">Already have an account? Login.</a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
{% endblock %}

userControl/templates/userControl/registration_form_MDL.html
{% extends 'main/base_MDL.html' %}
{% block title %}Registration{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'userControl/style_MDL.css' %}" />
{% endblock %}

{% block body %}
    <div class="mdl-layout mdl-js-layout">
        <div class="mdl-layout_content">
            <div class="mdl-card mdl-shadow--6dp">
                <div class="mdl-card__title">
                    <h2 class="text-logo">Sign up to the Mothership</h2>
                </div>
                <div class="mdl-card__supporting-text">
                    {% if error_message %}
                        <p>{{ error_message }}</p>
                    {% endif %}

                    <form id="registrationForm" class="site_form" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                {{ field }}
                                <input class="mdl-textfield__label" for="{{ field.id_for_label }}">{{ field.placeholder }}</input>
                            </div>
                        {% endfor %}

                        <div class="mdl-card__actions mdl-card--border">
                            <button type="sumbit" class="mdl-button mdl-js-button mdl-js-ripple-effect">Register</button>
                        </div>

                        <div class="form-group text-center">
                            <br>
                            <a href="{% url 'userControl:login' %}">Already have an account? Login.</a>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

userControl/templates/userControl/user_detail.html
{% extends 'main/base.html' %}

{% block title %}Account Details{% endblock %}

{% block static %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'userControl/style.css' %}" />
{% endblock %}

{% block body %}
    <h1>Account Details</h1>
    <p>Username: {{ user.username }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>

    <br>
    <!-- User this when sorted out: % url 'userControl:user-update' user.id % -->
    <form action="" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-default btn-sm">Edit</button>
    </form>

    <br>
    <br>
    <br>
    <hr>
    <br>
    <form action="{% url 'userControl:apitoken-create' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default btn-sm">Generate API Key</button>
    </form>
    <br>
    {% if api_tokens %}
        <ul>
            {% for token in api_tokens %}
            <li>{{ token.key }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No API tokens</p>
    {% endif %}


{% endblock %}